-- pds
REVOKE SELECT,UPDATE ON responsible FROM ora00057;
REVOKE SELECT ON purchase_pds FROM ora00057;
-- SKS
REVOKE select ON part_sks FROM ora00059;
--sk
REVOKE SELECT,UPDATE ON part_sk  FROM ora00137;
REVOKE SELECT,UPDATE ON purchase_sk FROM ora00137;

--pa
REVOKE SELECT ON part_pa FROM ora00123;
