-- pds
REVOKE SELECT,UPDATE ON responsible FROM user057;
REVOKE SELECT ON part FROM user057;
REVOKE SELECT ON pa_agent FROM user057;
REVOKE SELECT ON purchase_pds FROM user057;
-- SKS
REVOKE select ON part_sks FROM user059;
REVOKE UPDATE,SELECT ON responsible FROM user059;
--sk
REVOKE SELECT,UPDATE ON part_sk  FROM user137;
REVOKE SELECT,UPDATE ON purchase_sk FROM user137;
REVOKE SELECT,UPDATE ON part  FROM user137;
REVOKE UPDATE ON purchase_order FROM user137;
REVOKE SELECT,UPDATE ON detail FROM user137;
--pa
REVOKE SELECT,INSERT ON detail FROM user123;
REVOKE SELECT,INSERT ON contractual FROM user123;
REVOKE SELECT,INSERT ON pa_task FROM user123;
REVOKE SELECT,INSERT ON purchase_order FROM user123;
REVOKE SELECT ON part_pa FROM user123;
REVOKE SELECT ON pot_supplier_pa FROM user123;
REVOKE SELECT ON part FROM user123;
-- Tech is DBA